hydra:
  run:
    dir: outputs/classifier_${hydra.job.config_name}-${now:%Y-%m-%d}-${now:%H-%M-%S}
  job: 
    chdir: True
hyperparameters:
  learning_rate: 1e-5
  batch_size: 64
model:
  num_layers: 12
  hidden_size: 80
data: 
  name: snsf
logger: False
  
