hydra:
  run:
    dir: outputs/classifier_${hydra.job.config_name}-${now:%Y-%m-%d}-${now:%H-%M-%S}
  job: 
    chdir: True
hyperparameters:
  learning_rate: 1e-4
  batch_size: 32
model:
  num_layers: 12
  hidden_size: 80
data: 
  name: snsf
logger: True

  
