hydra:
  run:
    dir: outputs/classifier_${hydra.job.config_name}-${now:%Y-%m-%d}-${now:%H-%M-%S}
  job: 
    chdir: True
hyperparameters:
  learning_rate: 1e-3
  batch_size: 10
  epochs: 100
model:
  num_layers: 4
  hidden_size: 10
data: 
  name: sonar
logger: True
stopper:
  patience: 10
  min_delta: 0.0005