hydra:
  run:
    dir: outputs/classifier_${hydra.job.config_name}-${now:%Y-%m-%d}-${now:%H-%M-%S}
  job: 
    chdir: True
hyperparameters:
  learning_rate: 1e-4
  weight_decay: 1e-6
  batch_size: 32
  epochs: 300
optimizer: Adam # or SGD
model:
  num_layers: 10
  hidden_size: 60
data: 
  name: ssnf
  target_only: False
  corrected: False # either train on corrected MC + data or uncorrected MC + data
  dummy_weights: False # either a number or False
logger: True
stopper:
  patience: 10
  min_delta: 0.0005
checkpoints:
  data: /work/tfluehma/git/SSNF2/outputs/base_cfg_zuko0_data_eb-2023-10-26-10-22-54
  mc : /work/tfluehma/git/SSNF2/outputs/base_cfg_zuko0_mc_eb-2023-11-01-10-52-57
  top: /work/tfluehma/git/SSNF2/outputs/top_cfg_zuko_mdmm4_eb-2023-11-08-13-03-33
fff_model:
  name: zuko_nsf
  ntransforms: 12
  nbins: 16
  nnodes: 512
  nlayers: 4
  penalty: l1
  penalty_weight: 0.1
  anneal: 0
context_variables:
  - probe_pt
  - probe_eta
  - probe_phi
  - probe_fixedGridRhoAll
target_variables:
  - probe_r9
  - probe_s4
  - probe_sieie
  - probe_sieip
  - probe_etaWidth
  - probe_phiWidth
  - probe_pfPhoIso03
  - probe_pfChargedIsoPFPV
  - probe_pfChargedIsoWorstVtx