hydra:
  run:
    dir: output/classifier_${hydra.job.config_name}-${now:%Y-%m-%d}-${now:%H-%M-%S}
  job: 
    chdir: True
hyperparameters:
  learning_rate: 1e-4
  batch_size: 64
model:
  num_layers: 10
  hidden_size: 50

  
