hydra:
  run:
    dir: outputs/base_${hydra.job.config_name}_${sample}_${calo}-${now:%Y-%m-%d}-${now:%H-%M-%S}
  job:
    chdir: True
sample: data
calo: eb
pipelines: pipe0
context_variables:
  - probe_pt
  - probe_eta
  - probe_phi
  - probe_fixedGridRhoAll
target_variables:
  - probe_r9
  - probe_s4
  - probe_sieie
  - probe_sieip
  - probe_etaWidth
  - probe_phiWidth
  - probe_pfPhoIso03
  - probe_pfChargedIsoPFPV
  - probe_pfChargedIsoWorstVtx
train:
  size: 1500000
  batch_size: 2048
test:
  size: 100000
  batch_size: 2048
model:
  maf:
    num_steps: 6
    num_transform_blocks: 3
    dropout_probability: 0.0
    use_residual_blocks: True
    batch_norm: True
    hidden_dim: 64
  arqs:
    num_steps: 10
    num_transform_blocks: 4
    dropout_probability: 0.1
    use_residual_blocks: True
    batch_norm: True
    hidden_dim: 300
    num_bins: 32
    tail_bound: 5.0
  activation: relu
  init_identity: True
  transform_type: rq-autoregressive
optimizer:
  learning_rate: 1e-4
  beta1: 0.9
  beta2: 0.999
  weight_decay: 1e-5
stopper:
  patience: 10
  min_delta: 0.2
#distributed: True
distributed: False
epochs: 200
sample_every: 10
checkpoint: null
