hydra:
  run:
    dir: outputs/top_${hydra.job.config_name}_${calo}-${now:%Y-%m-%d}-${now:%H-%M-%S}
  job:
    chdir: True
calo: eb
pipelines: pipe1
context_variables:
  - probe_pt
  - probe_eta
  - probe_phi
  - probe_fixedGridRhoAll
target_variables:
  - probe_r9
  - probe_s4
  - probe_sieie
  - probe_sieip
  - probe_etaWidth
  - probe_phiWidth
  - probe_pfPhoIso03
  - probe_pfChargedIsoPFPV
  - probe_pfChargedIsoWorstVtx
train:
  size: 1500000
  batch_size: 2048
test:
  size: 100000
  batch_size: 2048
data:
<<<<<<< HEAD
  checkpoint: /work/tfluehma/git/SSNF2/outputs/base_cfg_zuko0_data_eb-2023-10-26-10-22-54
mc:
  checkpoint: /work/tfluehma/git/SSNF2/outputs/base_cfg_zuko0_mc_eb-2023-11-01-10-52-57
=======
  checkpoint: /work/gallim/devel/CQRRelatedStudies/SSNF2/outputs/base_cfg_zuko0_data_eb-2023-10-30-17-34-31
mc:
  checkpoint: /work/gallim/devel/CQRRelatedStudies/SSNF2/outputs/base_cfg_zuko0_mc_eb-2023-10-30-17-34-23
>>>>>>> 2ae5eef4c8fbc6808f1eeeea1b3d526d1bdbbe8b
model:
  name: zuko_nsf
  ntransforms: 12
  nbins: 16
  nnodes: 512
  nlayers: 3
  penalty: l1
  penalty_weight: 0.005
  anneal: 0
mdmm:
  max: 0.005
  scale: 10000
  damping: 100
optimizer:
  learning_rate: 1e-4
  beta1: 0.9
  beta2: 0.999
  weight_decay: 1e-5
stopper:
  patience: 15
  min_delta: 0.05
#distributed: True
distributed: False
epochs: 200
sample_every: 5
checkpoint: null
